apiVersion: apps/v1
kind: Deployment
metadata:
  name: bartenders
  labels:
    app: bartenders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bartenders
  template:
    metadata:
      labels:
        app: bartenders
    spec:
      imagePullSecrets:
        - name: artifact-read
      containers:
        - name: bartenders
          image: us-east1-docker.pkg.dev/bartenders-464918/docker-us/bartenders:${IMAGE_TAG}
          ports:
            - containerPort: 8000
          imagePullPolicy: IfNotPresent